// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://swwvzvrefrywvbwheskq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3d3Z6dnJlZnJ5d3Zid2hlc2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODYxMjgsImV4cCI6MjA3MzU2MjEyOH0.Zz7UnEkZVa8riDc450DPYMiZWZUQ4ZG8fkiz9iyJ_h0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});